#include <furi.h>
#include <gui/gui.h>
#include <gui/icon_i.h>
#include <gui/view_dispatcher.h>
#include <gui/scene_manager.h>
#include <gui/modules/menu.h>
#include <gui/modules/popup.h>

/* Tutorial: https://instantiator.dev/post/flipper-zero-app-tutorial-02/ */

/* generated by fbt from .png files in images folder */
#include <test_app_icons.h>

typedef enum {
    TestAppScene_MainMenu,
    TestAppScene_FirstPopup,
    TestAppScene_SecondPopup,
    TestAppScene_count
} TestAppScene;

typedef struct {
    SceneManager* scene_manager;
    ViewDispatcher* view_dispatcher;
    Menu* menu;
    Popup* popup;
} TestApp;

typedef enum { TestAppEvent_ShowPopupOne, TestAppEvent_ShowPopupTwo } TestAppEvent;

typedef enum { TestAppView_Menu, TestAppView_Popup } TestAppView;

TestApp* test_app_init() {
    TestApp* app = malloc(sizeof(TestApp));
    test_app_scene_manager_init(app);
    test_app_view_dispatcher_init(app);
}

int32_t test_app_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm test_app!");

    return 0;
}
